# Generated by Django 4.2.27 on 2025-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('cif', models.CharField(max_length=20, unique=True, verbose_name='NIF/CIF')),
                ('nombre_contacto', models.CharField(max_length=100, verbose_name='Persona de contacto')),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección Fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='SKU / Ref')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('coste', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coste Compra')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PVP Venta')),
                ('iva', models.IntegerField(choices=[(21, '21%'), (10, '10%'), (4, '4%'), (0, '0%')], default=21)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
