# Generated by Django 4.2.27 on 2025-12-11 18:58

from django.db import migrations, models


def crear_estados_iniciales(apps, schema_editor):
    """Crear los estados iniciales del pedido"""
    Estado = apps.get_model('core', 'Estado')
    estados = [
        {'codigo': 'BORRADOR', 'nombre': 'Borrador', 'descripcion': 'Pedido en borrador'},
        {'codigo': 'CONFIRMADO', 'nombre': 'Confirmado', 'descripcion': 'Pedido confirmado'},
        {'codigo': 'FACTURADO', 'nombre': 'Facturado', 'descripcion': 'Pedido facturado'},
        {'codigo': 'COBRADO', 'nombre': 'Cobrado', 'descripcion': 'Pedido cobrado'},
    ]
    for estado_data in estados:
        Estado.objects.get_or_create(**estado_data)


def eliminar_estados(apps, schema_editor):
    """Eliminar los estados (operación inversa)"""
    Estado = apps.get_model('core', 'Estado')
    Estado.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedido',
                'ordering': ['codigo'],
            },
        ),
        migrations.RunPython(crear_estados_iniciales, eliminar_estados),
    ]
