# Generated by Django 4.2.27 on 2025-12-11 18:58

from django.db import migrations, models
import django.db.models.deletion


def migrar_estados_a_foreignkey(apps, schema_editor):
    """Migrar los valores de CharField a ForeignKey"""
    Pedido = apps.get_model('ventas', 'Pedido')
    Estado = apps.get_model('core', 'Estado')
    
    # Migrar cada pedido
    for pedido in Pedido.objects.all():
        # Acceder al valor del CharField antiguo directamente desde la BD
        codigo_antiguo = pedido.estado  # Esto es el CharField antiguo
        try:
            estado_nuevo = Estado.objects.get(codigo=codigo_antiguo)
            pedido.estado_fk = estado_nuevo
            pedido.save()
        except Estado.DoesNotExist:
            # Si no existe, usar BORRADOR por defecto
            estado_por_defecto = Estado.objects.get(codigo='BORRADOR')
            pedido.estado_fk = estado_por_defecto
            pedido.save()


def revertir_estados_a_charfield(apps, schema_editor):
    """Revertir ForeignKey a CharField (operación inversa)"""
    Pedido = apps.get_model('ventas', 'Pedido')
    Estado = apps.get_model('core', 'Estado')
    
    for pedido in Pedido.objects.all():
        if pedido.estado_fk:
            pedido.estado = pedido.estado_fk.codigo
            pedido.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estado'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        # Primero agregar el nuevo campo ForeignKey como nullable temporalmente
        migrations.AddField(
            model_name='pedido',
            name='estado_fk',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pedidos_fk',
                to='core.estado'
            ),
        ),
        # Migrar los datos
        migrations.RunPython(migrar_estados_a_foreignkey, revertir_estados_a_charfield),
        # Eliminar el campo CharField antiguo
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        # Renombrar el nuevo campo
        migrations.RenameField(
            model_name='pedido',
            old_name='estado_fk',
            new_name='estado',
        ),
        # Hacer el campo no nullable
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pedidos',
                to='core.estado'
            ),
        ),
    ]
