# Generated by Django 4.2.27 on 2025-12-11 18:59

from django.db import migrations, models
import django.db.models.deletion
import ventas.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estado'),
        ('ventas', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(default=ventas.models.get_estado_borrador, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.estado'),
        ),
    ]
